Adds all necessary updates for new release of testnet.

diff --git a/launchmevcommit b/launchmevcommit
--- a/launchmevcommit
+++ b/launchmevcommit
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 # Initialize variables
-RPC_URL="http://69.67.151.95:8545"
+RPC_URL="http://chainrpc.testnet.mev-commit.xyz:8545"
 NODE_TYPE=""
 ROOT_DIRECTORY="$HOME/.mev-commit"
-MEV_COMMIT_VERISON="v0.1.2-rc5"
+MEV_COMMIT_VERISON="v0.2.0"
 # Define the base URL for downloading the mev-commit release
 BASE_URL="https://github.com/primevprotocol/mev-commit/releases/download/$MEV_COMMIT_VERISON"
 
@@ -31,8 +31,8 @@ while [[ "$#" -gt 0 ]]; do
 done
 
 # Check if RPC_URL and NODE_TYPE are provided
-if [ -z "$RPC_URL" ] || [ -z "$NODE_TYPE" ]; then
-    echo "Error: Missing required arguments."
+if [ -z "$NODE_TYPE" ]; then
+    echo "Error: Missing required argument --node-type."
     usage
 fi
 
@@ -87,22 +87,6 @@ if [ ! -d ~/.foundry/bin ]; then
     $HOME/.foundry/bin/foundryup
 fi
 
-# check if ROOT_DIRECTORY exists; if it does, ask user if they want to overwrite
-# if [ -d "$ROOT_DIRECTORY" ]; then
-#     echo -e "\033[31m[\033[34m*\033[31m]\033[33m $ROOT_DIRECTORY already exists. Do you want to overwrite it? [y/n]\033[0m"
-#     read -r OVERWRITE
-#     if [ "$OVERWRITE" == "y" ]; then
-#         rm -rf $ROOT_DIRECTORY
-#     else
-#         # Start mev-commit with the config file
-#         if ! $ROOT_DIRECTORY/mev-commit start --config=$ROOT_DIRECTORY/config.yaml; then
-#             echo "Failed to start mev-commit with the specified config."
-#             exit 1
-#         fi
-#     fi
-# fi
-
-
 # Create the target directory if it doesn't exist
 mkdir -p $ROOT_DIRECTORY
 
@@ -119,10 +103,10 @@ fi
 cd $ROOT_DIRECTORY
 
 echo -e "\033[31m[\033[34m*\033[31m]\033[33m Initializing mev-commit...\033[0m"
-./mev-commit --settlement-rpc-endpoint $RPC_URL --peer-type $NODE_TYPE --bidder-registry-contract $BIDDER_REGISTRY_CONTRACT --provider-registry-contract $PROVIDER_REGISTRY_CONTRACT --preconf-contract $PRECONF_CONTRACT --bootnodes /ip4/69.67.151.95/tcp/13522/p2p/16Uiu2HAmLYUvthfDCewNMdfPhrVefBbsfaPL22fWWfC2zuoh5SpV & 
+./mev-commit --settlement-rpc-endpoint $RPC_URL --peer-type $NODE_TYPE --bootnodes /dnsaddr/bootnode.testnet.mev-commit.xyz & 
 server_pid=$!
 
-sleep 3
+sleep 5
 
 KEY=$(cat $ROOT_DIRECTORY/key)
 ADDRESS=$(cast wallet address --private-key 0x$(cat $ROOT_DIRECTORY/key))
@@ -142,7 +126,7 @@ if [ "$NODE_TYPE" == "provider" ]; then
     echo -e "\033[31m[\033[34m*\033[31m]\033[33m Registering $ADDRESS as a provider with 50 ether stake \033[0m"
 
     # Use the RPC URL variable in the cast send command
-    if ! $HOME/.foundry/bin/cast send $PROVIDER_REGISTRY_CONTRACT "registerAndStake()" $ADDRESS --rpc-url http://69.67.151.95:8545 --private-key $KEY --value 50ether > /dev/null 2>&1; then
+    if ! $HOME/.foundry/bin/cast send $PROVIDER_REGISTRY_CONTRACT "registerAndStake()" $ADDRESS --rpc-url "$RPC_URL" --private-key $KEY --value 50ether > /dev/null 2>&1; then
             echo "Failed to send provider registration transaction."
             exit 1
     fi
